name: CI/CD Pipeline for Java with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Проверка исходного кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Docker
      - name: Set up Docker
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Сборка Docker-образа
      - name: Build Docker Image
        run: docker build -t java-ci-cd-demo .

      # Запуск тестов внутри Docker-контейнера
      - name: Run Tests
        run: docker run --rm java-ci-cd-demo ./mvnw test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Проверка исходного кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Деплой на Render
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"serviceId":"srv-ctpae0d2ng1s73boikcg"}' \
          https://api.render.com/v1/services/srv-ctpae0d2ng1s73boikcg/deploys
